version: '3.5'

services:

  react-babel-webpack-boilerplate:
    image: react-babel-webpack-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8081:8081'
    environment:
      - NODE_ENV=development
